name: 'pull-request'

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v6'

      - uses: 'astral-sh/setup-uv@v7'
        with:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'

      - run: |
          uv sync --locked --all-extras --dev

      - run: |
          uv run pytest

      - run: |
          uv run ruff check .
          uv run ruff format --check .
          uv run ty check
